
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-ai_tracker}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ai_tracker}
      POSTGRES_DB: ${POSTGRES_DB:-ai_tracker}
    volumes:
      - ./backend/.data/postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build: ./backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    depends_on:
      - db
    volumes:
      - ./backend/app:/app/app
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres-data:
    driver: local


