[phases.setup]
nixPkgs = ["nodejs_18", "python3", "pip"]

[phases.install]
cmds = [
  "npm install",
  "cd frontend && npm install",
  "cd ../backend_python && pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "cd frontend && npm run build"
]

[start]
cmd = "bash start.sh"
