[tool.briefcase]
project_name = "Expenses Tracker"
bundle = "com.example"
version = "0.1.0"
url = "https://example.com"
license = "Proprietary"
author = "AI Tracker"
author_email = "dev@example.com"

[tool.briefcase.app.expenses_tracker]
formal_name = "Expenses Tracker"
description = "App di monitoraggio spese con backend FastAPI"
icon = "src/expenses_tracker/resources/expenses_tracker"
sources = ["src/expenses_tracker"]
requires = [
    "toga==0.4.7",
    "requests==2.32.3",
    "matplotlib==3.9.2",
    "travertino==0.3.0"
]

[tool.briefcase.app.expenses_tracker.macOS]
requires = ["toga-cocoa==0.4.7"]

[tool.briefcase.app.expenses_tracker.linux]
requires = ["toga-gtk==0.4.7"]

[tool.briefcase.app.expenses_tracker.windows]
requires = ["toga-winforms==0.4.7"]

[tool.briefcase.app.expenses_tracker.iOS]
requires = ["toga-iOS==0.4.7"]

[tool.briefcase.app.expenses_tracker.android]
requires = ["toga-android==0.4.7"]


